# Generated by Django 3.1.2 on 2020-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('tipo', models.CharField(choices=[('L', 'Lente'), ('E', 'Estuche'), ('G', 'Gotita')], max_length=1)),
            ],
        ),
    ]
